---
- name: clone drush from github
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "{{ drush_install_dir }}"
    version: "{{ drush_git_version }}"
    update: "{{ drush_git_update }}"
    force: "{{ drush_git_force_update }}"
  register: drush_clone

- name: install drush dependencies
  shell: >
    {{ composer_exec }} install {{ drush_composer_cli_options }}
    chdir={{ drush_install_dir }}
  when: drush_clone.changed

- name: create drush exec link
  file: src={{ drush_install_dir }}/drush dest={{ drush_exec }} state=link
